### ISSUE TITLE
No API to access real-time section information

### ISSUE THREAD

**Issue by mark695073649** [Purdue-io/PurdueApi#16]
I tried dropping a class and test how long it takes to be seen on the api, but it seems to take a really long time (more than 10 minutes, still waiting)

**Comment by haydenmc** [comment]
This is related to #6 - the user authenticated APIs were last minute and relatively untested (adding and dropping CRNs in particular is tough to test), which is part of the reason it doesn't appear in the wiki documentation. 

I'll try to look into this more. 

Thanks!

**Comment by haydenmc** [comment]
That is unless you're referring to the delay in seat count information updating when you add/drop. I can fill you in on the plan for addressing that if that's the issue. :)

**Comment by mark695073649** [comment]
yeah I was just looking at the seat count, the "RemainingSpace" to be specific.

**Comment by haydenmc** [comment]
Gotcha - 

Purdue.io works by actually pulling down the entire course catalog for semesters at a given interval and mapping them to its own relational database of [course catalog entities](https://github.com/Purdue-io/PurdueApi/wiki/OData-Entities). This is something that [CatalogSync](https://github.com/Purdue-io/PurdueApi/tree/dev/CatalogSync) is responsible for. The reason we do this instead of just scraping the data on-demand is two-fold: performance, and relational queries. 

Right now the production instance at https://api.purdue.io pulls down the course catalog once every few hours (earlier the scraping and mapping process would take on the order of 1-2 hours, but some recent perf improvements have this down to 20 - 30 minutes). So the first order of business might be to reduce the time between scrapes.

Currently what this means, though, is that the class data is outdated on the order of hours, as you observed, which is particularly relevant to timely information like seating. We considered this when designing the original API - the solution was to be an authenticated API endpoint that you could pass a CRN to get a real-time scraping of the data, guaranteeing it was up to date. I'm not sure we finished adding that endpoint, but it should be fairly trivial to implement, given it's doing what CatalogSync already does (scraping class data). 

Hope this brings some clarity as to how it works - I'll look into the authenticated lookup endpoint and see if it's trivial to get it working.

**Comment by haydenmc** [comment]
Should be resolved by #17 - see the [new docs](https://github.com/Purdue-io/PurdueApi/wiki/Authenticated-Endpoints#get-studentcrntermcodecrn).
